module ForemanDebian
  module EngineHelper

    def setup
      @exported = []
      @output = ForemanDebian::logger
    end

    def pidfile(name)
      name = "#{@app}-#{name}"
      Pathname.new('/var/run').join(name).join(name + '.pid')
    end

    def cleanup
      each_file do |path|
        next if @exported.include? path
        remove_file path
      end
    end

    def export_file(path)
      @exported.push(path)
      @output.info " create  #{path.to_s} "
    end

    def remove_file(path)
      File.unlink path
      @output.info " remove  #{path.to_s}"
    end

    def each_file(&block)
      Dir.glob @export_path.join("#{@app}-*") do |path|
        path = Pathname.new(path)
        next unless path.read.match(/# Autogenerated by foreman/)
        block.call(path)
      end
    end

    def exec_command(command)
      `#{command}`
    end
  end
end
