module ForemanDebian
  module Engine::Helper

    def setup
      @exported = []
      @output = $stdout
    end

    def pidfile(name)
      name = "#{@app}-#{name}"
      Pathname.new('/var/run').join(name).join(name + '.pid')
    end

    def cleanup
      Dir.glob @export_path.join("#{@app}-*") do |path|
        path = Pathname.new(path)
        next unless path.read.match(/# Autogenerated by foreman/)
        next if @exported.include? path
        remove_file path
      end
    end

    def export_file(path)
      @exported.push(path)
      @output.puts " create  #{path.to_s} "
    end

    def remove_file(path)
      File.unlink path
      @output.puts " remove  #{path.to_s}"
    end
  end
end
